const questions = [
    { text: "Socialism can only be realised in developed/industrialised societies.", targets: { a2a: 1, a4a: 0.5, a6a: 1 } },
    { text: "Nationalism and patriotism are impulses that are unacceptable in a socialist society.", targets: { a2a: 0.5, a4a: 1, a4c: 0.5 } },
    { text: "Only a mass workers party can achieve any meaningful long-term goals.", targets: { a2c: 0.5, a3a: 1, a3b: 0.5, a5a: 1, a5b: 0.5 } },
    { text: "Rather than an open mass party, a revolutionary organization must consist of a highly disciplined cadre of dedicated militants who intervene within broader worker organs.", targets: { a3a: 0.5, a3b: 1, a5a: 1, a5c: 0.5 } },
    { text: "Large-scale enterprises must be socialized, but small-scale private property can be permitted as long as it operates ethically and without exploitation.", targets: { a3c: 1, a8b: 1, a8c: 1 } },
    { text: "All the means of production, such as factories and farms, must be owned and controlled directly by the workers themselves.", targets: { a3b: 0.5, a5b: 0.5, a5c: 1, a8a: 1 } },
    { text: "Some small scale destruction of nature is acceptable if it notably benefits humanity.", targets: { a6a: 1, a6c: 0.5 } },
    { text: "The fact that so many workers vote for bourgeois parties over socialist parties is proof that party politics are no longer relevant.", targets: { a1a: 0.5, a1c: 1, a2c: 1, a3c: 0.5, a5b: 0.5, a5c: 0.5 } },
    { text: "'From each according to their ability, to each according to their needs' is a good principle.", targets: { a2a: 0.5, a2b: 1, a6c: 1, a8a: 1 } },
    { text: "The socialist principle 'He who does not work, neither shall he eat' is a necessary and correct baseline for society.", targets: { a6a: 1, a8b: 1, a8c: 1 } },
    { text: "Reforming capitalist society via elections to achieve better rights for workers is desirable.", targets: { a1b: 1, a2b: 0.5, a2c: 1, a3a: 1, a4b: 0.5, a5a: 0.5 } },
    { text: "Mutual aid is a valid method to build power in capitalist society.", targets: { a1c: 1, a2b: 1, a2c: 0.5, a3c: 1, a4c: 1 } },
    { text: "In underdeveloped societies a centrally planned economy is the best way to make rapid progress.", targets: { a1b: 0.5, a2c: 1, a3a: 1, a3b: 0.5, a4b: 1, a5a: 1, a6a: 1, a8c: 1 } },
    { text: "Socialist political parties should participate in liberal democratic elections to implement reforms.", targets: { a1b: 1, a2c: 1, a3a: 0.5, a3b: 0.5, a4b: 0.5, a4c: 0.5, a5a: 1, a8c: 1 } },
    { text: "Unions should seek official recognition from the state and employers to secure legal rights and implement gradual reforms.", targets: { a2c: 1, a3a: 0.5, a3c: 0.5, a5b: 1, a8c: 0.5 } },
    { text: "Modern social democracy is a betrayal of left-wing values.", targets: { a1a: 0.5, a1c: 0.5, a2a: 0.5, a2b: 1 } },
    { text: "Measures to address environmental issues are unacceptable if they result in significant decreases in production and quality of life.", targets: { a6b: -1 } },
    { text: "A centrally planned economy based around computers is a concept worth investigating.", targets: { a3a: 0.5, a3b: 1, a3c: 0.5 } },
    { text: "Trade unionism has been largely corrupted by the ruling class and is no longer a viable structure for a socialist organization.", targets: { a5a: 1, a5c: 0.5 } },
    { text: "Despite their working-class origins, trade unions function primarily to negotiate the terms of wage labor within capitalism, rendering them incapable of achieving revolutionary change.", targets: { a1a: 1, a2a: 1, a5a: 0.5, a5c: 0.5 } },
    { text: "A disciplined socialist party can capture and transform existing trade unions into revolutionary organs of struggle.", targets: { a3a: 1, a3b: 0.5, a5a: 1, a5b: 1 } },
    { text: "Rather than working through restrictive trade unions, revolutionaries must encourage workers to self-organize through spontaneous strike committees and autonomous mass assemblies.", targets: { a1a: 1, a3b: 0.5, a3c: 0.5, a5a: 0.5, a5c: 1 } },
    { text: "Because permanent economic organizations like trade unions inevitably become integrated into state-capitalist structures, only a dedicated political organization can remain a viable, permanent vehicle for struggle.", targets: { a2a: 0.5, a3b: 0.5, a5a: 1, a5c: 0.5 } },
    { text: "The transition from capitalism to socialism is a gradual process that inevitably requires a prolonged transitional stage.", targets: { a2a: 1 } },
    { text: "It is preferable to achieve socialism gradually via reforms rather than through a violent revolution.", targets: { a1b: 1, a2c: 1, a2b: 1, a3a: 1, a5a: 1 } },
    { text: "Trade unions can serve as highly effective tools to organize labor and minimize work stoppages for the sake of national development.", targets: { a2c: 1, a3a: 1, a4b: 1, a5b: 1, a6a: 1, a8c: 1 } },
    { text: "Local planners, rather than national planners, are more efficient at managing a planned economy.", targets: { a1c: 0.5, a3b: -0.5, a3c: 1, a4c: 1, a5b: 0.5, a5c: 0.5 } },
    { text: "Experimental environmentally-friendly food sources like cultured meat are worth investing in.", targets: { a6c: 1, a7: 1 } },
    { text: "Personal motor vehicles, such as cars, should be replaced with free public transport.", targets: { a6c: 1 } },
    { text: "Marriage is a patriarchal social construct that should be phased out.", targets: { a7: 1 } },
    { text: "Democratic centralism, when properly implemented, emphasizes collective decision-making rather than top-down commands.", targets: { a3b: 1 } },
    { text: "Revolutionary violence is justified if the final outcome is positive.", targets: { a1a: 1 } },
    { text: "A successful revolution is made possible by objective material conditions, and cannot be achieved by the sheer willpower of revolutionaries alone.", targets: { a2a: 1 } },
    { text: "A socialist government has no right to disrupt or dismantle traditional religious and cultural practices, regardless of the circumstances.", targets: { a7: -1 } },
    { text: "Redistributing wealth through progressive taxation is a viable way to defeat social and economic inequality.", targets: { a1b: 1, a2c: 1, a3a: 1, a8c: 1 } },
    { text: "We must acknowledge that twentieth-century socialist states largely failed to seriously address environmental issues.", targets: { a6b: 1 } },
    { text: "Bureaucracy and inefficiency are inherent features of centrally planned economies.", targets: { a3c: 1 } },
    { text: "A socialist revolution is made inevitable by the conditions of capitalism, unless nuclear armageddon or total ecological collapse occurs first.", targets: { a1a: 1, a2a: 1 } },
    { text: "Industrialized farming practices must be abolished, even if it leads to lower food production outputs.", targets: { a6b: 1 } },
    { text: "Human population growth must be actively curbed to prevent global ecological disaster.", targets: { a6b: 1 } },
    { text: "An economy is generally better when it is organized bottom-up rather than top-down.", targets: { a3b: 0.5, a3c: 1 } },
    { text: "It is foolish to expect renewable energy sources to be able to replace fossil fuels.", targets: { a6a: 1 } },
    { text: "A socialist world is a realistic and desirable goal.", targets: { a4a: 1 } },
    { text: "Socialism and communism are identical; a transitional phase should not be classified as a distinct 'socialist' stage of development.", targets: { a1a: 1, a2a: 1 } },
    { text: "The oppression of LGBTQ+ people is a major issue that needs to be fought.", targets: { a7: 1 } },
    { text: "Workplace democracy within capitalism is an acceptable alternative to a complete socialization of the economy.", targets: { a1b: 1, a3c: 1 } },
    { text: "A highly centralized planned economy is not socialism but rather state capitalism.", targets: { a3b: 0.5, a3c: 0.5, a4a: 1, a5b: 0.5, a5c: 0.5, a8a: 1 } },
    { text: "Traditional gender roles, such as women being homemakers, need to be overcome.", targets: { a7: 1 } },
    { text: "Class conflict is a force that has influenced much of human history.", targets: { a2a: 1 } },
    { text: "Policies that permit mass immigration are naïve and should not be implemented.", targets: { a4b: 1, a4c: 0.5, a7: -1 } },
    { text: "Minority populations should receive special legal protections.", targets: { a4a: 1, a7: 1 } },
    { text: "The proletariat—encompassing all wage-laborers across industry, services, and agriculture—is the sole revolutionary class in capitalist society, whereas the petty bourgeoisie is inherently incapable of revolutionary action.", targets: { a2a: 1, a8a: 1 } },
    { text: "Mass spontaneous actions are more effective than carefully planned actions.", targets: { a3c: 1, a5c: 1 } },
    { text: "To survive and succeed, a socialist revolution must be actively spread beyond its original national borders.", targets: { a4a: 1 } },
    { text: "A socialist society should be built on a dual foundation of trade unions and confederations of small, independent businesses.", targets: { a5b: 1, a8b: 1 } },
    { text: "Workers' councils must serve as the supreme organs of both political and economic power in a socialist society.", targets: { a3b: 1, a3c: 1, a5c: 1, a8a: 1 } },
    { text: "Capitalism will inevitably collapse due to its own internal contradictions and systemic crises.", targets: { a2a: 1 } },
    { text: "Socialist organizations function more effectively when structured along decentralized and horizontal lines.", targets: { a3c: 1 } },
    { text: "People of similar cultural backgrounds should organize themselves into autonomous revolutions, federations or confederations.", targets: { a1b: 1, a1c: 1, a4b: 1, a4c: 1 } },
    { text: "The working class has no nation.", targets: { a4a: 1 } },
    { text: "'No War but the Class War' is a good slogan to rally behind.", targets: { a4a: 1 } },
    { text: "In the imperialist phase of capitalism, national liberation struggles provide no utility to the broader working-class movement.", targets: { a4a: 1 } },
    { text: "In the Global South, the primary contradiction is imperialism, meaning we must prioritize defeating imperialist domination before we can successfully struggle against capitalism.", targets: { a1c: 1, a2c: 1, a4b: 1, a4c: 0.5 } },
    { text: "Every nation on the planet is capitalist, meaning our struggle must be a direct, global fight against the entire world's bourgeoisie.", targets: { a4a: 1, a8a: 1 } },
    { text: "To counter Western hegemony, leftists must offer critical support to states opposing NATO imperialism, even if those nations are not strictly socialist.", targets: { a1c: 1, a4b: 1, a8c: 1 } },
    { text: "A socialist society should be willing to divert its own economic resources to support revolutionary struggles and development abroad, even at its own expense.", targets: { a4a: 1 } },
    { text: "The Bolshevik Revolution was a genuine proletarian revolution that ultimately degenerated due to its isolation and the failure of the international socialist revolution.", targets: { a2a: 1, a4a: 1 } },
    { text: "The bureaucratic degeneration of the early Soviet Union could have been averted simply by replacing its top political leadership.", targets: { a2b: 1, a3a: 1 } },
    { text: "Achieving total economic and social equality is a realistic and attainable goal for human society.", targets: { a2b: 1 } },
    { text: "We must radically alter our food consumption patterns in order to limit the exploitation of nature.", targets: { a6b: 1 } },
    { text: "The state should have the authority to assign individuals to specific workplaces based on economic planning needs.", targets: { a3a: 1 } },
    { text: "The negative consequences of a revolution generally outweigh its advantages.", targets: { a1b: 1 } },
    { text: "The ruling class can be peacefully persuaded to accept a transition to a socialist society.", targets: { a1b: 1 } },
    { text: "The working class must subordinate itself to the authority of a revolutionary party to guarantee a successful transition to socialism.", targets: { a3a: 1 } },
    { text: "Abortion is an immoral act that should be banned or significantly limited.", targets: { a7: -1 } },
    { text: "Material conditions and needs are the dominant drive behind socioeconomic changes.", targets: { a2a: 1 } },
    { text: "Establishing a dictatorship of the proletariat is a necessary transitional stage between capitalism and socialism.", targets: { a3b: 1, a3a: 0.5, a8a: 1 } },
    { text: "A socialist society goes hand in hand with significant social progress.", targets: { a7: 1 } },
    { text: "The global socialist movement should be directed by a single, unified international party or organization.", targets: { a3a: 1, a4a: 1, a5a: 1 } },
    { text: "An international confederation of syndicates is necessary to coordinate the global revolutionary struggle non-hierarchically.", targets: { a3c: 1, a4a: 1, a5b: 1 } },
    { text: "Religions overall have a mostly positive effect and should remain influential in society.", targets: { a7: -1 } },
    { text: "Implementing extensive environmental protections is a fundamental component of achieving socialism.", targets: { a6b: 1, a6c: 1 } },
    { text: "To overcome long-term climate and ecological crises, humanity must abandon industrialization and return to primitive ways of living.", targets: { a3c: 1, a6b: 1 } },
    { text: "National liberation, or the self-determination of all peoples, is a necessary and desirable concept.", targets: { a1c: 1, a2b: 1, a4b: 1, a4c: 1 } },
    { text: "It is acceptable for humanity to endure notable material hardships if it is necessary to preserve the natural ecosystem.", targets: { a6b: 1 } },
    { text: "Human history and society are chiefly driven by the ideas and willpower of individuals.", targets: { a2b: 1 } },
    { text: "Climate change is an existential global threat that all socialists must fiercely combat.", targets: { a6b: 1 } },
    { text: "It is possible to construct socialism primarily through establishing cooperatives and voluntary communes.", targets: { a1c: 1, a2b: 1, a3c: 1, a4c: 1 } },
    { text: "It is possible to successfully establish and sustain socialism within a single country.", targets: { a2c: 1, a4b: 1, a4c: 0.5 } }
];

Object.size = function(obj) {
    if (Array.isArray(obj)) return obj.length;
    let size = 0, key;
    for (key in obj) { if (obj.hasOwnProperty(key)) size++; }
    return size;
};
